FROM koenlek/ros-nvidia:kinetic-desktop-full

ENV LANG C.UTF-8

# NON ROOT USER ACCESS
ARG USERNAME=uzer
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \  
    python3 \ 
    python3-pip \
    g++ \
    # replaced libgl1 \ 
    libgl1-mesa-glx-lts-xenial \ 
    libglib2.0-0 \  
    libsm6 \ 
    libxext6 \ 
    net-tools

RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-$ROS_DISTRO-moveit-ros-visualization

# Pepper robot dependencies including base, moveit
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-$ROS_DISTRO-pepper-robot \
    ros-$ROS_DISTRO-pepper-dcm-bringup \
    ros-$ROS_DISTRO-pepper-moveit-config

# depenedencies for gazebo
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-$ROS_DISTRO-gazebo-ros \
    ros-$ROS_DISTRO-gazebo-ros-pkgs \
    ros-$ROS_DISTRO-gazebo-ros-control \
    ros-$ROS_DISTRO-effort-controllers \
    ros-$ROS_DISTRO-joint-trajectory-controller

# dependencies for pepper bringup
RUN apt-get update && apt-get install -y \
    ros-$ROS_DISTRO-driver-base \
    ros-$ROS_DISTRO-move-base-msgs \
    ros-$ROS_DISTRO-octomap \
    ros-$ROS_DISTRO-octomap-msgs \
    ros-$ROS_DISTRO-humanoid-msgs \
    ros-$ROS_DISTRO-humanoid-nav-msgs \
    ros-$ROS_DISTRO-camera-info-manager \
    ros-$ROS_DISTRO-camera-info-manager-py

# naoqi driver
RUN apt-get update && apt-get install -y \
    ros-$ROS_DISTRO-naoqi-driver

USER $USERNAME

# Pepper robot dependencies
RUN mkdir -p /home/$USERNAME/catkin_ws/src && \
    cd /home/$USERNAME/catkin_ws/src && \
    # pepper robot for description rviz file
    git clone https://github.com/ros-naoqi/pepper_robot.git && \
    # virtual - control + gazebo
    git clone https://github.com/ros-naoqi/pepper_virtual.git && \
    # naoqi dcm driver
    git clone https://github.com/ros-naoqi/naoqi_dcm_driver.git

RUN cd /home/uzer/catkin_ws && /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.sh && catkin_make"

RUN echo "source /opt/ros/$ROS_DISTRO/setup.sh" >> "/home/$USERNAME/.bashrc"
RUN echo "source /home/uzer/catkin_ws/devel/setup.bash" >> "/home/$USERNAME/.bashrc"